import crypto from "crypto";
import { PaymentRepository } from "../repositories/payment.repository";
import { waService } from "../utils/whatsapp";
import { NotifikasiService } from "./notifikasi.service";
import prisma from "../config/prisma";

// eslint-disable-next-line @typescript-eslint/no-var-requires
const midtransClient = require('midtrans-client');

const snap = new midtransClient.Snap({
  isProduction: false,
  serverKey: process.env.MIDTRANS_SERVER_KEY || 'SB-Mid-server-eiI-mROAGApUNj7hn4VCm4Nj',
  clientKey: process.env.MIDTRANS_CLIENT_KEY || 'SB-Mid-client-RDSS_US8FGGFBgXg'
});

export class PaymentService {
  static async initiatePayment(tagihanId: number, metode: string): Promise<{
    pembayaran: any;
    midtransResponse?: any;
    checkoutUrl?: string;
    message?: string;
  }> {
    const tagihan = await PaymentRepository.findTagihanById(tagihanId);

    if (!tagihan) throw new Error("Tagihan not found");
    if (tagihan.status === "LUNAS") throw new Error("Tagihan is already paid");

    const referenceId = `PAY-${Date.now()}-${crypto.randomBytes(4).toString("hex")}`;
    
    const pembayaran = await PaymentRepository.createPembayaran({
      tagihan: { connect: { id: tagihan.id } },
      metode: metode || "QRIS",
      jumlahBayar: tagihan.totalNominal,
      referenceId,
      status: "PENDING"
    });

    // CASH: tidak perlu payment gateway, langsung dicatat sukses (Bendahara konfirmasi offline)
    if (metode?.toUpperCase() === "CASH") {
      const keterangan = `Pembayaran Iuran Cash Bpk/Ibu ${tagihan.warga.kepalaKeluarga} (Bulan ${tagihan.bulan}/${tagihan.tahun})`;
      await PaymentRepository.executePaymentSuccessTransaction(
        pembayaran.id, tagihan.id, tagihan.totalNominal, keterangan
      );
      return { pembayaran, message: "Pembayaran cash berhasil dicatat" };
    }

    const parameter = {
      "transaction_details": {
        "order_id": referenceId,
        "gross_amount": tagihan.totalNominal
      },
      "customer_details": {
        "first_name": tagihan.warga.kepalaKeluarga.substring(0, 50),
        "email": tagihan.warga.user?.email || "warga@civichub.id",
        "phone": tagihan.warga.noTelepon || "081111111111"
      }
    };

    try {
      const transaction = await snap.createTransaction(parameter);
      return { 
        pembayaran, 
        midtransResponse: transaction,
        checkoutUrl: transaction.redirect_url 
      };
    } catch (midtransError) {
      console.error('Midtrans Error:', midtransError);
      return { 
        pembayaran, 
        checkoutUrl: `https://mock-payment-gateway.com/checkout/${referenceId}`,
        message: "Payment initiated (Mock Fallback)"
      };
    }
  }

  static async handleWebhook(reqBody: any) {
    const { order_id, transaction_status, status_code, gross_amount, signature_key } = reqBody; 
    
    // 🔒 1. VALIDASI SIGNATURE KEY (MENCEGAH WEBHOOK SPOOFING)
    const serverKey = process.env.MIDTRANS_SERVER_KEY || 'SB-Mid-server-eiI-mROAGApUNj7hn4VCm4Nj';
    const expectedHash = crypto.createHash('sha512')
      .update(`${order_id}${status_code}${gross_amount}${serverKey}`)
      .digest('hex');
    
    // Hanya enforce validasi di production; di sandbox/dev bisa dilewati untuk testing
    const isProduction = process.env.NODE_ENV === "production";
    if (isProduction && signature_key !== expectedHash) {
      throw new Error("Invalid signature key! Suspected spoofing.");
    }

    const referenceId: string = order_id || reqBody.referenceId;

    // Tentukan status berdasarkan transaction_status dari payment gateway
    const isSuccess = transaction_status === 'settlement' || transaction_status === 'capture';
    const isFailed = ['cancel', 'deny', 'expire'].includes(transaction_status) || reqBody.status === 'FAILED';
    const status: 'SUCCESS' | 'FAILED' | 'PENDING' = isSuccess ? 'SUCCESS' : isFailed ? 'FAILED' : 'PENDING';

    const pembayaran = await PaymentRepository.findPembayaranByReferenceId(referenceId);
    if (!pembayaran) throw new Error("Payment not found");

    if (status === "SUCCESS" && pembayaran.status !== "SUCCESS") {
      await PaymentRepository.executePaymentSuccessTransaction(
        pembayaran.id,
        pembayaran.tagihanId,
        pembayaran.jumlahBayar,
        `Pembayaran Iuran Bpk/Ibu ${pembayaran.tagihan.warga.kepalaKeluarga} VIA DIGITAL (Bulan ${pembayaran.tagihan.bulan})`
      );

      if (pembayaran.tagihan.warga.noTelepon) {
        const pesan = `*KWITANSI DIGITAL RT*\n\nTerima kasih Bpk/Ibu ${pembayaran.tagihan.warga.kepalaKeluarga},\nPembayaran Iuran bulan ${pembayaran.tagihan.bulan}-${pembayaran.tagihan.tahun} sebesar \n*Rp ${pembayaran.jumlahBayar.toLocaleString("id-ID")}* telah LUNAS.\n\n_Auto-Generated by CivicHub System_`;
        await waService.sendMessage(pembayaran.tagihan.warga.noTelepon, pesan);
      }

      // Notifikasi via App ke Warga
      await NotifikasiService.create({
        title: "Pembayaran Berhasil",
        message: `Pembayaran Iuran bulan ${pembayaran.tagihan.bulan}-${pembayaran.tagihan.tahun} sukses.`,
        userId: pembayaran.tagihan.warga.userId
      });

      // Notifikasi via App ke Bendahara
      const bendaharas = await prisma.user.findMany({ where: { role: "ADMIN_KEUANGAN" } });
      for (const b of bendaharas) {
        await NotifikasiService.create({
          title: "Pemasukan Iuran Baru",
          message: `Warga ${pembayaran.tagihan.warga.kepalaKeluarga} telah membayar sebesar Rp${pembayaran.jumlahBayar}`,
          userId: b.id
        });
      }

      return "SUCCESS";
    } else if (status === "FAILED") {
      await PaymentRepository.updatePembayaranStatus(pembayaran.id, "FAILED");
      return "FAILED";
    }
    
    return "PENDING";
  }
}
